'use client';
import {useEffect,useRef,useState} from 'react';
import {CheckCircle2,Eraser,FileSignature,Loader2} from 'lucide-react';
import {recordToProduct} from '@/lib/product-record';
import {useSiteContent} from '@/lib/use-site-content';

const defaultContractText=`1. KONU VE ÜRÜN: Bu sözleşme, müşterinin seçtiği abiye ürününün belirtilen tarihler arasında kiralanmasına ilişkin teslim, kullanım ve iade esaslarını düzenler.

2. TESLİM VE İADE: Ürün, tarafların belirlediği tarihte teslim alınır ve iade tarihinde mağazaya eksiksiz olarak teslim edilir. Gecikme halinde mağazanın güncel gecikme koşulları uygulanır.

3. KULLANIM VE BAKIM: Müşteri ürünü özenle kullanmayı; üründe izinsiz tadilat, kesim, boyama veya temizleme işlemi yapmamayı kabul eder.

4. HASAR VE KAYIP: Olağan kullanım dışındaki yırtılma, kalıcı leke, yanık, aksesuar kaybı veya ürünün kullanılamaz hale gelmesi durumunda hasar tespit tutanağı düzenlenir. Uygulanacak bedel mağazanın onaylı kiralama koşullarına göre belirlenir.

5. İPTAL VE DEĞİŞİKLİK: İptal, tarih değişikliği ve ücret iadesi mağazanın müşteriye işlem öncesinde bildirdiği güncel kurallara tabidir.

6. KİŞİSEL VERİLER: Sözleşmede yer alan bilgiler, kiralama işleminin kurulması, yürütülmesi, ispatı ve yasal yükümlülüklerin yerine getirilmesi amaçlarıyla işlenir.

7. ONAY: Müşteri ürün, tarih ve iletişim bilgilerinin doğru olduğunu; sözleşmeyi okuyup anladığını ve kendi iradesiyle onayladığını kabul eder.

Bu metin geçici taslaktır. Yayına alınmadan önce işletme bilgileri, ücretler, depozito, hasar, iptal ve yetkili mahkeme maddeleri hukuk danışmanı tarafından onaylanmalıdır.`;

export function RentalContractForm(){const content=useSiteContent(),contractText=content.rentalContract?.text||defaultContractText,canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),[products,setProducts]=useState<any[]>([]),[form,setForm]=useState({customerName:'',phone:'',email:'',productName:'',productColor:'',rentalStart:'',rentalEnd:'',depositNote:''}),[consent,setConsent]=useState(false),[signed,setSigned]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[error,setError]=useState('');
useEffect(()=>{const params=new URLSearchParams(location.search),selected=params.get('urun')||'',selectedColor=params.get('renk')||'',date=params.get('tarih')||'';setForm(x=>({...x,productName:selected,productColor:selectedColor,rentalStart:date,rentalEnd:date}));fetch('/api/products').then(r=>r.json()).then(d=>{const live=(d.items||[]).map(recordToProduct).filter((p:any)=>p.type.includes('Kiralık'));setProducts(live);setForm(x=>{const productName=x.productName||live[0]?.name||'',product=live.find((p:any)=>p.name===productName);return{...x,productName,productColor:x.productColor||product?.colorVariants?.[0]?.name||''}})}).catch(()=>{});const c=canvas.current;if(!c)return;const ratio=Math.max(devicePixelRatio||1,1),w=c.clientWidth,h=c.clientHeight;c.width=w*ratio;c.height=h*ratio;const ctx=c.getContext('2d')!;ctx.scale(ratio,ratio);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.strokeStyle='#171512'},[]);
const point=(e:React.PointerEvent)=>{const r=canvas.current!.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
const start=(e:React.PointerEvent)=>{drawing.current=true;canvas.current!.setPointerCapture(e.pointerId);const p=point(e),ctx=canvas.current!.getContext('2d')!;ctx.beginPath();ctx.moveTo(p.x,p.y)};
const move=(e:React.PointerEvent)=>{if(!drawing.current)return;const p=point(e),ctx=canvas.current!.getContext('2d')!;ctx.lineTo(p.x,p.y);ctx.stroke();setSigned(true)};
const clear=()=>{const c=canvas.current!,ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);setSigned(false)};
const selectedProduct=products.find((p:any)=>p.name===form.productName);
const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!signed)return setError('Lütfen imzanızı kutuya atın.');if(!consent)return setError('Sözleşme onayını işaretleyin.');setBusy(true);const r=await fetch('/api/contracts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,contractText,signature:canvas.current!.toDataURL('image/png'),consent})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error||'Sözleşme kaydedilemedi.');setResult(d)};
if(result)return <section className="contract-success"><CheckCircle2/><h2>Kiralama talebiniz alındı.</h2><p>Sözleşmeniz güvenle kaydedildi. Ekibimiz tarih ve ürün uygunluğunu son kez kontrol ederek sizinle iletişime geçecektir.</p><span>Sözleşme numaranız</span><strong>{result.contract_code}</strong><small>{result.emailSent?'Teyit e-postası adresinize gönderildi.':'Teyit e-postası gönderilemedi. Bu numarayı saklayın; talebiniz yönetim paneline iletildi.'}</small></section>;
return <form className="contract-form" onSubmit={submit}><section className="contract-fields"><h2>Kiralama bilgileri</h2><div className="contract-grid"><label>Ad Soyad<input required value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/></label><label>Telefon<input required type="tel" minLength={10} maxLength={20} inputMode="tel" placeholder="05XX XXX XX XX" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>E-posta<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Ürün<select required value={form.productName} onChange={e=>{const product=products.find((p:any)=>p.name===e.target.value);setForm({...form,productName:e.target.value,productColor:product?.colorVariants?.[0]?.name||''})}}><option value="">Ürün seçin</option>{products.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label>Renk<select required value={form.productColor} onChange={e=>setForm({...form,productColor:e.target.value})}><option value="">Renk seçin</option>{(selectedProduct?.colorVariants||[]).map((variant:any)=><option key={variant.name} value={variant.name}>{variant.name}</option>)}</select></label><label>Teslim tarihi<input required type="date" min={new Date().toISOString().slice(0,10)} value={form.rentalStart} onChange={e=>setForm({...form,rentalStart:e.target.value,rentalEnd:form.rentalEnd<e.target.value?e.target.value:form.rentalEnd})}/></label><label>İade tarihi<input required type="date" min={form.rentalStart||new Date().toISOString().slice(0,10)} value={form.rentalEnd} onChange={e=>setForm({...form,rentalEnd:e.target.value})}/></label></div><label>Depozito / özel not<textarea value={form.depositNote} onChange={e=>setForm({...form,depositNote:e.target.value})}/></label></section><section className="contract-document"><div className="contract-title"><FileSignature/><div><p>SÖZLEŞME SÜRÜMÜ 1.0</p><h2>Abiye Kiralama Koşulları</h2></div></div><pre>{contractText}</pre><label className="contract-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Sözleşmenin tamamını okudum, anladım ve kabul ediyorum.</span></label><div className="signature-head"><b>Müşteri imzası</b><button type="button" onClick={clear}><Eraser/> Temizle</button></div><canvas ref={canvas} className="signature-pad" onPointerDown={start} onPointerMove={move} onPointerUp={()=>drawing.current=false} onPointerCancel={()=>drawing.current=false}/><small>Parmağınızla veya farenizle yukarıdaki alana imza atın.</small>{error&&<p className="contract-error">{error}</p>}<button className="contract-submit" disabled={busy}>{busy?<><Loader2/> Kaydediliyor…</>:<>Sözleşmeyi imzala ve talep oluştur</>}</button></section></form>}

