create extension if not exists pgcrypto;
create type public.app_role as enum ('super_admin','content_manager','product_manager','appointment_staff');
create type public.appointment_status as enum ('new','pending','confirmed','contacted','arrived','completed','cancelled','no_show');
create table public.profiles(id uuid primary key references auth.users on delete cascade, full_name text, created_at timestamptz default now());
create table public.user_roles(user_id uuid references public.profiles on delete cascade, role app_role not null, primary key(user_id,role));
create table public.stores(id uuid primary key default gen_random_uuid(), name text not null, timezone text not null default 'Europe/Istanbul', address text, phone text, active boolean default true, created_at timestamptz default now());
create table public.services(id uuid primary key default gen_random_uuid(), name text not null, duration_minutes int not null check(duration_minutes between 15 and 480), buffer_minutes int not null default 15, capacity int not null default 1 check(capacity>0), active boolean default true);
create table public.working_hours(id bigint generated always as identity primary key, store_id uuid references public.stores on delete cascade, weekday int check(weekday between 0 and 6), opens_at time, closes_at time, unique(store_id,weekday));
create table public.blocked_times(id uuid primary key default gen_random_uuid(), store_id uuid references public.stores, starts_at timestamptz not null, ends_at timestamptz not null, reason text, check(ends_at>starts_at));
create table public.customers(id uuid primary key default gen_random_uuid(), first_name text not null, last_name text not null, phone text not null, email text not null, consent_at timestamptz not null, created_at timestamptz default now());
create table public.categories(id uuid primary key default gen_random_uuid(), parent_id uuid references public.categories, name text not null, slug text unique not null, sort_order int default 0, visible boolean default true);
create table public.collections(id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, visible boolean default true);
create table public.products(id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, slug text unique not null, description text, rental_price numeric(12,2), sale_price numeric(12,2), price_visible boolean default true, status text default 'draft' check(status in('draft','published','archived')), featured boolean default false, new_arrival boolean default false, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.product_categories(product_id uuid references public.products on delete cascade, category_id uuid references public.categories on delete cascade, primary key(product_id,category_id));
create table public.product_collections(product_id uuid references public.products on delete cascade, collection_id uuid references public.collections on delete cascade, primary key(product_id,collection_id));
create table public.product_media(id uuid primary key default gen_random_uuid(), product_id uuid references public.products on delete cascade, path text not null, media_type text default 'image', alt_text text, sort_order int default 0, is_cover boolean default false);
create table public.appointments(id uuid primary key default gen_random_uuid(), appointment_code text unique not null default ('HC-'||upper(substr(encode(gen_random_bytes(6),'hex'),1,8))), customer_id uuid references public.customers, store_id uuid references public.stores, service_id uuid references public.services, starts_at timestamptz not null, ends_at timestamptz not null, status appointment_status default 'new', cancel_token_hash text not null default encode(digest(gen_random_uuid()::text,'sha256'),'hex'), notes text, created_at timestamptz default now(), updated_at timestamptz default now(), archived_at timestamptz);
create index appointments_store_time_idx on public.appointments(store_id,starts_at) where archived_at is null and status not in('cancelled','no_show');
create table public.notifications(id uuid primary key default gen_random_uuid(), kind text not null, title text not null, body text, read_at timestamptz, created_at timestamptz default now());
create table public.audit_logs(id bigint generated always as identity primary key, actor_id uuid, action text not null, entity text not null, entity_id uuid, metadata jsonb default '{}', created_at timestamptz default now());
alter table public.products enable row level security; alter table public.categories enable row level security; alter table public.collections enable row level security; alter table public.appointments enable row level security; alter table public.customers enable row level security; alter table public.user_roles enable row level security;
create policy "published products public" on public.products for select using(status='published' and deleted_at is null);
create policy "visible categories public" on public.categories for select using(visible);
create policy "visible collections public" on public.collections for select using(visible);
create or replace function public.create_public_appointment(p_payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_service services; v_store stores; v_start timestamptz; v_count int; v_customer uuid; v_appt appointments;
begin
 select * into v_service from services where name=p_payload->>'service' and active limit 1; if not found then raise exception 'service_unavailable'; end if;
 select * into v_store from stores where active limit 1; if not found then raise exception 'store_unavailable'; end if;
 v_start:=((p_payload->>'date')||' '||(p_payload->>'time'))::timestamp at time zone v_store.timezone;
 if v_start < now()+interval '2 hours' then raise exception 'booking_too_soon'; end if;
 perform pg_advisory_xact_lock(hashtextextended(v_store.id::text||v_start::text,0));
 select count(*) into v_count from appointments where store_id=v_store.id and starts_at=v_start and status not in('cancelled','no_show') and archived_at is null;
 if v_count>=v_service.capacity then raise exception 'capacity_exceeded'; end if;
 insert into customers(first_name,last_name,phone,email,consent_at) values(p_payload->>'firstName',p_payload->>'lastName',p_payload->>'phone',p_payload->>'email',now()) returning id into v_customer;
 insert into appointments(customer_id,store_id,service_id,starts_at,ends_at) values(v_customer,v_store.id,v_service.id,v_start,v_start+make_interval(mins=>v_service.duration_minutes)) returning * into v_appt;
 insert into notifications(kind,title,body) values('appointment','Yeni randevu',v_appt.appointment_code);
 return jsonb_build_object('appointment_code',v_appt.appointment_code);
end $$;
revoke all on function public.create_public_appointment(jsonb) from public,anon,authenticated; grant execute on function public.create_public_appointment(jsonb) to service_role;
alter publication supabase_realtime add table public.appointments,public.notifications;
